spring:
  datasource:
    master: # 写账户
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123
    slave1: # 只读账户
      jdbc-url: jdbc:mysql://localhost:3306/test_slave1?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123
    slave2: # 只读账户
      jdbc-url: jdbc:mysql://localhost:3306/test_slave2?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123
